config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end

  resources :courses
  resources :evaluations, controller: 'evaluations'
  resources :students, controller: 'students'
  resources :evaluation_results
  resources :evaluation_result_reports
  root to: redirect('/users/sign_in')

end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :course
  has_many :evaluation_results, dependent: :restrict_with_error
  validates_associated :course
  validates :title, presence: true
  validates :evaluation_date, presence: true
  validates :evaluation_date, date: true
  validates :evaluation_date, date: { after: Proc.new { Date.today }, message: ' debe ser futura.'}
  validates :minimum_note, presence: true
  validates :minimum_note, numericality: { only_integer: true }

  after_create :createStudentEvaluations

  def self.ids_by_course_id(course_id)
    Evaluation.where(course_id).pluck(:id)
    end

  def self.by_evaluation_ids(evaluation_ids)
    Evaluation.joins(:course).where('evaluations.id' => evaluation_ids).order('evaluation_date')
  end

  def createStudentEvaluations
    @students = Student.where(:course_id => course_id)
    @students.each do |student|
      EvaluationResult.create(:note => 0, :student_id => student.id, :evaluation_id => id)
    end
  end

end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
  before_action :authenticate_user!, unless: :devise_controller?
  before_action :set_evaluation, only: [:show, :edit, :update, :destroy]

  # GET /evaluations
  def index
    if params.has_key?(:course)
      @evaluations = Evaluation.where(course_id: params[:course][:course_id])
    else
      @evaluations = Evaluation.all
    end
  end

  # GET /evaluations/new
  def new
    @courses = Course.all
    @evaluation = Evaluation.new
  end

  # GET /evaluations/1/edit
  def edit
    @courses = Course.all
    @evaluation = Evaluation.find(params[:id])
  end

  # POST /evaluations
  # POST /evaluations.json
  def create
    @evaluation = Evaluation.new(evaluation_params)
    @courses = Course.all
    respond_to do |format|
      if @evaluation.save
        format.html { redirect_to action: "index", notice: 'Se creó la evaluación exitosamente.' }
      else
        format.html {render :new}
        format.js { render json: @evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluations/1
  # PATCH/PUT /evaluations/1.json
  def update
    @courses = Course.all
    @evaluation = Evaluation.find(params[:id])
    respond_to do |format|
      if @evaluation.update(evaluation_params)
        format.html { redirect_to action: "index", notice: 'Se actualizó la evaluación exitosamente.' }
      else
        format.html { render :edit }
        format.json { render json: @evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluations/1
  # DELETE /evaluations/1.json
  def destroy
    if @evaluation.destroy
      flash['success'] = "Evaluación eliminada correctamente."
      redirect_to action: "index"
    else
      flash['error'] = "La evaluación no pudo ser eliminada. Existen Resultados que dependen de ella!"
      redirect_to evaluations_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evaluation
      @evaluation = Evaluation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evaluation_params
      params.require(:evaluation).permit(:course_id, :title, :evaluation_date, :minimum_note)
    end
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

app/views/evaluations/_form.html.erb
<div class="container-fluid">
  <div class="col-md-5">
    <div class="form-area">
      <%= form_with(model: @evaluation, local: true) do |form| %>
        <br style="clear:both">
        <div class="form-group row">
          <div class="col-md-12">
            <% if @evaluation.errors.any? %>
              <div id="error_explanation">
                <h7>No se pudo guardar. Hay <%= pluralize(@evaluation.errors.count, "error") %> :</h7>
                <ul>
                  <% @evaluation.errors.full_messages.each do |message| %>
                    <li class="text-danger"><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
          </div>
        </div>

        <div class="form-group" >
          <%= form.label :title, 'Año de Cursada', class: "control-label" %>
          <%= form.collection_select(:course_id, @courses, :id, :anio,  {:include_blank => "Seleccione una Cursada"}, {:class=>'btn btn-secondary dropdown-toggle form-control'}) %>
        </div>

        <div class="form-group" >
            <%= form.label :title, 'Descripción', class: "control-label" %>
            <%= form.text_field :title, id: :evaluation_title, class: "form-control" %>
        </div>

        <div class="form-group" >
            <%= form.label :evaluation_date, 'Fecha de Evaluación', class: "control-label" %>
            <%= form.date_select :evaluation_date, id: :evaluation_evaluation_date, class: "form-control" %>
        </div>

        <div class="form-group" >
            <%= form.label :minimum_note, 'Nota Mínima', class: "control-label" %>
            <%= form.text_field :minimum_note, id: :evaluation_minimum_note, class: "form-control" %>
        </div>

        <div class="modal-footer">
          <%= link_to 'Cancelar', evaluations_path %>
          <%= form.submit "Confirmar", class: "btn btn-default btn-primary"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/evaluations/edit.html.erb
<div class="modal-header">
  <h3 class="min-margin">Editar Evaluación</h3>
</div>
<div class="modal-body" >
    <%= render 'form', evaluation: @evaluation %>
</div>

app/views/evaluations/index.html.erb
<p id="notice"><%= notice %></p>
<br/>
<h3 class="min-margin"> Evaluaciones </h3>

<hr/>

<div class="form-row min-margin">
  <div class="min-margin">
    <label class="control-label">Año de Cursada</label>
  </div>

  <%= render partial: "shared/course_select", locals: { path: evaluations_path}  %>

</div>

<hr/>

<div class="min-margin">
  <%= button_to "Nueva Evaluación", new_evaluation_path, :method => :get, class: "btn btn-primary min-margin right"%>
</div>

<table class="table table-striped table-sm table-bordered">
  <thead class="thead-dark">
  <tr>
    <th>Evaluacion</th>
    <th>Fecha</th>
    <th>Año de Cursada</th>
    <th>Nota de Aprobación</th>
    <th colspan="2"></th>
  </tr>
  </thead>

  <tbody>
  <% @evaluations.each do |evaluation| %>
    <tr>
      <td><%= evaluation.title %></td>
      <td><%= evaluation.evaluation_date %></td>
      <td><%= evaluation.course.anio %></td>
      <td><%= evaluation.minimum_note %></td>
      <td><%= button_to "Editar", edit_evaluation_path(evaluation.id), :method => :get, class: "btn btn-sm btn-info" %>
      <td><%= link_to 'Eliminar', evaluation_path(evaluation), remote: true, :method => :delete,
                      data: {confirm: "¿Quiere eliminar esta evaluación: #{evaluation.title}?"}, :class => 'btn btn-sm btn-danger' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/evaluations/new.html.erb
<div class="modal-header">
  <h3 class="min-margin"> Nueva Evaluación </h3>
</div>
<div class="modal-body" >
  <%= render 'form', evaluation: @evaluation %>
</div>