config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end

  resources :courses
  resources :evaluations, controller: 'evaluations'
  resources :students, controller: 'students'
  resources :evaluation_results
  resources :evaluation_result_reports
  root to: redirect('/users/sign_in')

end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :course
  validates_associated :course
  validates :name, presence: true
  validates :surname, presence: true
  validates :dni, presence: true
  validates :student_number, presence: true
  validates :email, presence: true
  validates :email, :email_format => { :message => ', por favor ingrese un email correcto.' }

  after_create :createStudentEvaluations

  def createStudentEvaluations
    @evaluations = Evaluation.where(:course_id => course_id)
    @evaluations.each do |eval|
      EvaluationResult.create(:note => 0, :student_id => id, :evaluation_id => eval.id)
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!, unless: :devise_controller?
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    if params.has_key?(:course)
      @students = Student.where(course_id: params[:course][:course_id])
    else
      @students = Student.all
    end
  end

  # GET /students/new
  def new
    @courses = Course.all
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
    @courses = Course.all
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)
    @courses = Course.all
    respond_to do |format|
      if @student.save
        format.html { redirect_to action: "index", notice: 'Se creó el estudiante exitosamente.' }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    @courses = Course.all
    @student = Student.find(params[:id])
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to action: "index", notice: 'Se actualizó el estudiante exitosamente.' }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    begin
      if @student.destroy
        flash['success'] = "Alumno eliminado correctamente."
        redirect_to action: "index"
      else
        flash['error'] = "El alumno no pudo ser eliminado. Tiene Resultados relacionados."
      end
    rescue ActiveRecord::InvalidForeignKey
      flash['error'] = "El alumno no pudo ser eliminado. Tiene Resultados relacionados."
    end
    redirect_to students_path
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_student
    @student = Student.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def student_params
    params.require(:student).permit(:course_id, :name, :surname, :dni, :student_number, :email)
  end
end

app/helpers/students_helper.rb
module StudentsHelper

  def fullname
    "#{self.name} #{self.surname}"
  end

end

app/views/students/_form.html.erb
<div class="container-fluid">
  <div class="col-md-5">
    <div class="form-area">
      <%= form_with(model: student, local: true) do |form| %>
        <br style="clear:both">
        <% if @student.errors.any? %>
          <div id="error_explanation">
            <h7>No se pudo guardar. Hay <%= pluralize(@student.errors.count, "error") %> :</h7>
            <ul>
              <% @student.errors.full_messages.each do |message| %>
                <li class="text-danger"><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group" >
          <%= form.label :title, 'Año de Cursada', class: "control-label" %>
          <%= form.collection_select(:course_id, @courses, :id, :anio,  {:include_blank => "Please select"}, {:class=>'btn btn-secondary dropdown-toggle form-control'}) %>
        </div>

        <div class="form-group">
          <%= form.label :name, class: "control-label" %>
          <%= form.text_field :name, id: :student_name, class: "form-control"  %>
        </div>

        <div class="form-group">
          <%= form.label :surname, class: "control-label" %>
          <%= form.text_field :surname, id: :student_surname, class: "form-control"  %>
        </div>

        <div class="form-group">
          <%= form.label :dni, class: "control-label" %>
          <%= form.text_field :dni, id: :student_dni, class: "form-control"  %>
        </div>

        <div class="form-group">
          <%= form.label :student_number, class: "control-label" %>
          <%= form.text_field :student_number, id: :student_student_number, class: "form-control"  %>
        </div>

        <div class="form-group">
          <%= form.label :email, class: "control-label" %>
          <%= form.text_field :email, id: :student_email, class: "form-control"  %>
        </div>

        <div class="actions">
          <%= link_to 'Cancelar', students_path %>
          <%= form.submit "Confirmar", class: "btn btn-default btn-primary"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/students/edit.html.erb
<div class="modal-header">
  <h3 class="modal-title" id="exampleModalLabel">Editar Alumno</h3>
</div>
<div class="modal-body" >
  <%= render 'form', student: @student %>
</div>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h3 class="min-margin"> Alumnos </h3>
<hr/>
<div class="form-row min-margin">
  <div class="min-margin">
    <label class="control-label">Año de Cursada</label>
  </div>

  <%= render partial: "shared/course_select", locals: { path: students_path} %>

</div>
<hr/>
<div class="min-margin">
  <%= button_to "Agregar Estudiante", new_student_path, :method => :get, class: "btn btn-primary min-margin right"%>
</div>

<table class="table table-striped table-sm table-bordered">
  <thead class="thead-dark">
  <tr>
    <th>Nombre</th>
    <th>Apellido</th>
    <th>DNI</th>
    <th>Número de Legajo</th>
    <th>Año de Cursada</th>
    <th>Correo Electrónico</th>
    <th colspan="2"></th>
  </tr>
  </thead>

  <tbody>
  <% @students.each do |student| %>
    <tr>
      <td><%= student.name %></td>
      <td><%= student.surname %></td>
      <td><%= student.dni %></td>
      <td><%= student.student_number %></td>
      <td><%= student.course.anio %></td>
      <td><%= student.email %>
      <td><%= button_to "Editar", edit_student_path(student.id), :method => :get, class: "btn btn-sm btn-info" %>
      <td><%= link_to "Eliminar", student_path(student), remote: true, :method => :delete,
                      data: {confirm: "¿Quiere eliminar el estudiante: >#{student.surname}, #{student.name} de la cursada?"}, :class => 'btn btn-sm btn-danger' %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/students/new.html.erb
<div class="modal-header">
  <h3 class="min-margin">Crear Alumno</h3>
</div>
<div class="modal-body" >
  <%= render 'form', student: @student %>
</div>