config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end

  resources :courses
  resources :evaluations, controller: 'evaluations'
  resources :students, controller: 'students'
  resources :evaluation_results
  resources :evaluation_result_reports
  root to: redirect('/users/sign_in')

end

app/controllers/evaluation_result_reports_controller.rb
class EvaluationResultReportsController < ApplicationController
  before_action :authenticate_user!, unless: :devise_controller?

  def initialize
    super # this calls ActionController::Base initialize
    init_this
  end

  def index
    @courses = Course.all
    if params.has_key?(:course)
      @report = @reporter.report(course_id: params[:course][:course_id])
    else
      @reporter.report(nil)
    end
  end

  private

  def init_this
    @reporter = EvaluationsReporter.new
  end
end

app/helpers/evaluation_result_reports_helper.rb
module EvaluationResultReportsHelper
  def full_name(result)
    result.student_name + " " + result.student_surname
  end

  def set_status(status, date)
   if date.future? then
     return "Sin evaluar"
   end
    return status
  end

end

app/views/evaluation_result_reports/index.html.erb
<h3 class="min-margin">Resultados por Cursada</h3>

<%= form_with url: evaluation_result_reports_path, method: :get, local: true do |e| %>
  <div class="form-row min-margin">
    <div class="min-margin">
      <%= collection_select(:course, :course_id, Course.all, :id, :anio,  {:include_blank => "Cursadas"}, {:class=>'btn btn-secondary dropdown-toggle'}) %>
    </div>
    <div class="min-margin">
      <%= e.submit "Reportar", class: "btn btn-default btn-primary" %>
    </div>
  </div>
<% end %>

<div class="container-fluid">

  <h5>Resumen de Evaluaciones</h5>
  <table class="table table-striped table-sm table-bordered">
    <thead class="thead-dark">
    <% if @report.nil? then%>
      <tr>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td  colspan="5">
          <p>No hay datos para la opción seleccionada.</p>
        </td>
      </tr>
      </tbody>
    <% else %>
      <tr>
        <th> Nombre </th>
        <% @report.course_evaluations.each do |evaluation| %>
          <th><%= evaluation.title %></th>
        <% end %>
      </tr>
      </tr>
      </thead>
      <tbody>
      <% @report.course_evaluations_results.each do |student_result| %>
        <tr>
          <th><%= full_name(student_result) %> </th>
          <% student_result.evaluation_results.each do |eval_result| %>
            <td><%= eval_result.status %></td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    <% end %>
    </table>

  <h5>Resumen de Cursada</h5>

  <table class="table table-striped table-sm">
    <thead class="thead-dark">
    <tr>
      <th>Evaluación</th>
      <th>Aprobados</th>
      <th>Desaprobados</th>
      <th>Ausentes</th>
      <th>Porcentaje de Aprobacion</th>
    </tr>
    </thead>

    <tbody>
    <% if @report.nil? then%>
      <tr>
        <td  colspan="5">
          <p>No hay datos para la opción seleccionada.</p>
        </td>
      </tr>
    <% else %>
      <% @report.course_results.each do |course_result| %>
        <tr>
          <td><%= course_result.evaluation_name %></td>
          <td><%= course_result.approved %></td>
          <td><%= course_result.disapproved %></td>
          <td><%= course_result.absent %></td>
          <td><%= course_result.approved_percentage %></td>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>
</div>