config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end

  resources :courses
  resources :evaluations, controller: 'evaluations'
  resources :students, controller: 'students'
  resources :evaluation_results
  resources :evaluation_result_reports
  root to: redirect('/users/sign_in')

end

app/models/evaluation_result.rb
class EvaluationResult < ApplicationRecord
  belongs_to :student
  belongs_to :evaluation
  validates_associated :evaluation
  validates_associated :student
  validates :note, presence: true
  validates :note, numericality: { only_integer: true }, :allow_nil => true

  before_create :setEvaluationStatus
  before_update :setEvaluationStatus

  APPROVED = "Aprobado"
  DISAPPROVED = "Desaprobado"
  ABSENT = "Ausente"

  def self.by_evaluation_ids_with_order(evaluation_ids, order)
    EvaluationResult.includes(:evaluation).where(:evaluation_id => evaluation_ids).order(order)
  end

  def self.by_student_id_with_order(student_id, order)
    EvaluationResult.includes(:evaluation).where(:student_id => student_id).order(order)
  end

  def self.order_by_evaluation_date
    EvaluationResult.includes(:evaluation).all.order('evaluations.evaluation_date')
    end

  def self.by_course_by_evaluation_date(course_id)
    EvaluationResult.includes(:evaluation).merge(Evaluation.where(:course_id => course_id)).order('evaluations.evaluation_date')
  end

  def setEvaluationStatus
    if note == 0
      self.status = ABSENT
    else if note < evaluation.minimum_note
           self.status = DISAPPROVED
         else
           self.status = APPROVED
         end
    end
  end

end

app/controllers/evaluation_results_controller.rb
class EvaluationResultsController < ApplicationController
  respond_to :html, :json
  before_action :authenticate_user!, unless: :devise_controller?
  before_action :set_evaluation_result, only: [:show, :edit, :update, :destroy]

  # GET /evaluation_results
  # GET /evaluation_results.json
  def index
    if params.has_key?(:course)
      @evaluation_results = EvaluationResult.by_course_by_evaluation_date(params[:course][:course_id])
    else
      @evaluation_results = EvaluationResult.order_by_evaluation_date;
    end

  end

  # GET /evaluation_results/1/edit
  def edit
    @students = Student.all.uniq
  end

  # POST /evaluation_results
  # POST /evaluation_results.json
  def create
    @evaluation_result = EvaluationResult.new(evaluation_result_params)
    respond_to do |format|
      if @evaluation_result.save
        format.html { redirect_to action: "index", notice: 'Se creó la nota exitosamente.' }
      else
        format.html { render :new }
        format.json { render json: @evaluation_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluation_results/1
  # PATCH/PUT /evaluation_results/1.json
  def update
    @students = Student.all
    respond_to do |format|
      if @evaluation_result.update(evaluation_result_params)
        format.html { redirect_to action: "index", notice: 'Se actualizó la nota exitosamente.' }
        format.json { respond_with_bip(@evaluation_result) }
      else
        format.html { render :action => "index" }
        format.json { respond_with_bip(@evaluation_result) }
      end
    end
  end

  # DELETE /evaluation_results/1
  # DELETE /evaluation_results/1.json
  def destroy
    if @evaluation_result.destroy
      flash['success'] = "Resultado eliminado correctamente."
      redirect_to action: "index"
    else
      flash['error'] = "El resultado no pudo ser eliminado."
      redirect_to evaluation_result_path
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_evaluation_result
    @evaluation_result = EvaluationResult.find(params[:id])
  end

  def evaluation_result_params
    params.require(:evaluation_result).permit(:course_id, :student_id, :evaluation_id, :note)
  end
end

app/helpers/evaluation_results_helper.rb
module EvaluationResultsHelper
end

app/views/evaluation_results/_form.html.erb
<div class="container-fluid">
  <div class="col-md-5">
    <div class="form-area">
      <%= form_with(model: evaluation_result, local: true) do |form| %>
        <br style="clear:both">
        <% if evaluation_result.errors.any? %>
          <div id="error_explanation">
            <h7>No se pudo guardar. Hay <%= pluralize(@evaluation_result.errors.count, "error") %> :</h7>
            <ul>
              <% evaluation_result.errors.full_messages.each do |message| %>
                <li class="text-danger"><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :student_id, class: "control-label" %>
          <%= form.text_field :student_id, id: :evaluation_result_student_id, :disabled => true, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :evaluation_id, class: "control-label" %>
          <%= form.text_field :evaluation_id, id: :evaluation_result_evaluation_id, :disabled => true, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :note, class: "control-label" %>
          <%= form.number_field :note, id: :evaluation_result_note, class: "form-control" %>
        </div>

        <div class="modal-footer">
          <%= link_to 'Cancelar', evaluation_result_path %>
          <%= form.submit "Confirmar", class: "btn btn-default btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/evaluation_results/edit.html.erb
<div class="modal-header">
  <h3 class="min-margin">Editar Resultado</h3>
</div>
<div class="modal-body" >
  <%= render 'form', evaluation_result: @evaluation_result %>
</div>

app/views/evaluation_results/index.html.erb
<p id="notice"><%= notice %></p>

<h3 class="min-margin">Resultados</h3>
<hr/>
<div class="form-row min-margin">
  <div class="min-margin">
    <label class="control-label">Año de Cursada</label>
  </div>

  <%= render partial: "shared/course_select", locals: { path: evaluation_results_path} %>

</div>

<table class="table table-striped table-sm table-bordered">
  <thead class="thead-dark">
  <tr>
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Año de Cursada</th>
    <th>Evaluación</th>
    <th>Fecha de Evaluacion</th>
    <th>Nota</th>
    <th colspan="1"></th>
  </tr>
  </thead>

  <tbody>
  <% @evaluation_results.each do |evaluation_result| %>
    <tr>
      <td><%= evaluation_result.student.name %></td>
      <td><%= evaluation_result.student.surname %></td>
      <td><%= evaluation_result.evaluation.course.anio %></td>
      <td><%= evaluation_result.evaluation.title %></td>
      <td><%= evaluation_result.evaluation.evaluation_date %> </td>
      <td>
        <a data-toggle="tooltip" title="Editar Nota">
          <%= best_in_place evaluation_result, :note, :as => :input, :inner_class => 'input-align-center', :html_attrs => { size: 3} %>
        </a>
      </td>
      <td><%= link_to 'Eliminar', evaluation_result_path(evaluation_result), remote: true, :method => :delete,
                      data: {confirm: "¿Quiere eliminar este resultado: #{evaluation_result.evaluation.title}, para el estudiante: #{evaluation_result.student.surname} ?"}, :class => 'btn btn-sm btn-danger' %>    </tr>
  <% end %>
  </tbody>
</table>